### ISSUE TITLE
Old yanglint version

### ISSUE THREAD

**Issue by bclaise** [YangCatalog/backend#74] opened 2019-04-29 17:27 UTC
Do you have a cronjob job to update yanglint?
Actually, a cronjob to update all the 4 validators?

Regards, B.

**Comment by miroslavKovacPantheon** [comment] 2019-08-22 12:09
duplicate of #87

**Comment by miroslavKovacPantheon** [comment] 2019-08-22 12:10
Closing because of duplicity. Issue #87 stays allive.

**Closed** 2019-08-22 12:11 UTC
Labels: duplicate
