### ISSUE TITLE
Receiver container runs scripts under incorrect user

### ISSUE THREAD

**Issue by richardzilincikPantheon** [YangCatalog/backend#770] opened 2023-05-09 08:36 UTC
It seems like the receiver container is running scripts from the admin UI under the `root` user instead of the `yang` user. This can cause various permission issues.

**Comment by Fagtoy** [comment] 2023-06-01 09:57
The issue is resolved with this one: https://github.com/YangCatalog/backend/issues/779

**Closed by Fagtoy** 2023-06-01 09:57 UTC
Labels: bug
