### ISSUE TITLE
'unknown' compilation-status and empty compilation-result for module

### ISSUE THREAD

**Issue by SlavomirMazurPantheon** [YangCatalog/backend#276] opened 2021-05-19 13:31 UTC
**Current state:**
1. When module is added, we check whether there already is an compilation status/result for this module
2. If not, we set compilation-status to 'unknown' and create URL link to compilation-result, which is just empty HTML template
3. Then there is cronjob-weekly, which go through all the modules once a week and parse them and store compilation-status and compilation-results

**Problem:**
- compilation-result looks, like there was no problem during compilation -> it is empty ex.: https://yangcatalog.org/results/huawei-acl@2020-02-20_huawei.html). However, it is empty because there was no compilation yet.

**Proposed solution:**
EDIT: URL to the compilation-result should not be available until module was parsed by cronjob-weekly.

**Comment by bclaise** [comment] 2021-05-19 13:47
I don't understand what you mean by "URL to the compilation-result should not be available after HTML was created by cronjob-weekly."

Also, we want directly the compilation status. It was the case for IETF YANG module before. What has changed?

Regards, Benoit

**Comment by SlavomirMazurPantheon** [comment] 2021-05-19 14:06
Sorry, I updated the description:
URL to the compilation-result should not be available until module was parsed by cronjob-weekly.

**Comment by bclaise** [comment] 2021-05-19 14:34
That's what I feared. I'm afraid this "trick" is not an acceptable outcome. Waiting for up to 1 week to get a compilation status for a YANG module freshly uploaded... 
It was working before. It should work now.

**Comment by bclaise** [comment] 2021-05-28 06:44
Guys, I really need you to fix the issue that some Huawei YANG modules have an unknown "compilation-status"
ex: ://yangcatalog.org/yang-search/module_details/?module=huawei-acl

**Comment by SlavomirMazurPantheon** [comment] 2021-05-28 08:13
Sure, we are working on it right now

**Comment by SlavomirMazurPantheon** [comment] 2021-05-31 12:03
Compilation statuses and results are now available for Huawei modules.
**NOTE:** Please create PR to [YangModels/yang](https://github.com/YangModels/yang) repository, which will update huawei submodule to the latest version - master.

**Comment by bclaise** [comment] 2021-05-31 14:03
Vladimir, what was the root cause?

**Comment by bclaise** [comment] 2021-05-31 14:04
also, you're telling that I need a PR on YangModels/yang each time I do a change in https://github.com/Huawei/yang, as a trigger?

**Comment by bclaise** [comment] 2021-05-31 16:15
btw, look at the huawei-isis. Still not solved and the "compilation results" page is 404 NOT FOUND

**Comment by miroslavKovacPantheon** [comment] 2021-06-01 04:20
> 
> 
> also, you're telling that I need a PR on YangModels/yang each time I do a change in https://github.com/Huawei/yang, as a trigger?

yes because otherwise yangmodels/yang is pointing on old commit and it doesnt update modules according to your changes.

**Comment by SlavomirMazurPantheon** [comment] 2021-06-01 08:34
> btw, look at the huawei-isis. Still not solved and the "compilation results" page is 404 NOT FOUND

compilation result for this module is also available now. See: https://yangcatalog.org/results/huawei-isis@2020-08-03_huawei.html

**Comment by bclaise** [comment] 2021-06-01 10:31
did you solve this specific module only or a bigger problem? In other words, what was the root cause?

**Comment by SlavomirMazurPantheon** [comment] 2021-06-01 10:44
> did you solve this specific module only or a bigger problem? In other words, what was the root cause?

bigger problem - missing functionality (else branch) if HTML file was not created before - creation performed in backend, filling HTML with data performed in sdo-analysis during module compilation.
After fix we checked all the Huawei modules and did not found any where page was 404 NOT FOUND

Also we merged cronjob-daily (which parsed IETF modules) and cronjob-weekly (which parsed other vendors - like Huawei) cronjobs. This new cronjob will now run once a day and check SDO and vendor modules - no need to wait until weekend to parse vendor modules like situation from the previous week.

**Comment by evyncke** [comment] 2021-06-01 11:10
With enough CPU and bandwidth, let’s indeed scan all modules daily

From: SlavomirMazurPantheon ***@***.***>
Reply-To: YangCatalog/backend ***@***.***>
Date: Tuesday, 1 June 2021 at 12:45
To: YangCatalog/backend ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [YangCatalog/backend] 'unknown' compilation-status and empty compilation-result for module (#276)


did you solve this specific module only or a bigger problem? In other words, what was the root cause?

bigger problem - missing functionality (else branch) if HTML file was not created before - creation performed in backend, filling HTML with data performed in sdo-analysis during module compilation.
After fix we checked all the Huawei modules and did not found any where page was 404 NOT FOUND

Also we merged cronjob-daily (which parsed IETF modules) and cronjob-weekly (which parsed other vendors - like Huawei) cronjobs. This new cronjob will now run once a day and check SDO and vendor modules - no need to wait until weekend to parse vendor modules like situation from the previous week.

**Comment by SlavomirMazurPantheon** [comment] 2021-06-01 11:40
Currently, we are using file content hashing functionality which check whether the file content OR some of the validators versions changed. If no change - no compilation is needed, because it would result in same compilation status and result. It saves us a lot of time and also we do not compile same modules again and again.

This all resulted in possibility to merge two mentioned cronjobs into single one and run daily.

We also continuously check CPU and memory during the script run, when a large number of yang files are compiled (for example, when the validator version has been updated) and trying to achieve optimal load.

**Closed** 2022-02-24 09:00 UTC
Labels: Priorty: Medium, Maintenance
